Pathjava
SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018 pull request #12
Opened 2017-12-09 10:55 UTC by SamanthaDawsonBanks

I think this is path.java done, still needs testing and documentation so can people please check code is sane

2017-12-12 13:40 UTC, stevempope commented
A few things:

Path constructor - The initial length is 1 as we are handing the new path a destination.

With the length currently at 0, the Destination isn't on the path?

Are we not storing polled heads in a new Data Structure for reversal.

2017-12-12 13:41 UTC, stevempope requested changes
As my comment in the conversation 12-12-2017 at 13:40

2017-12-12 13:49 UTC, stevempope approved these changes

2017-12-12 13:51 UTC, stevempope commented
As discussed, the queue is a FIFO data structure, so that means the Destination cannot be returned until last. Length starts at 0 for the same reason.

I thought that we would have been dealing with a stack, but this was not the case.

2017-12-13 11:34 UTC, RyanShoobert approved these changes

2017-12-13 11:35 UTC, merged