Merging drive
SamanthaDawsonBanks/MCOMP_Team_Project_2017-2018 pull request #133
Opened 2018-03-22 17:13 UTC by stevempope

Requires #132 

Merges the logic from driving the motors with the maths.

Requires some refinement, see the //TODO messages.

2018-03-23 09:39 UTC, SamanthaDawsonBanks requested changes

2018-03-23 09:39 UTC, SamanthaDawsonBanks commented on mcomp_C/movement/Drive.cpp
> +	AngleDistance movement((atan2(w.getY(),w.getX())) * (180 / M_PI) , hypot(w.getX(),w.getY())); //TODO CHECK ATAN2 RETURN VALUE
as it is not really 'drivey' i pulled this line out into WP so there is now a Waypoint.toAngleDistance() #134 that will return a AD
so this line can become:
AngleDistance movement(w.toAngleDistance());

2018-03-23 09:39 UTC, SamanthaDawsonBanks commented on mcomp_C/maths/Forward.cpp
> +/*
I know i said root/math/ but probably worth moving this lot into movement?

2018-03-23 09:39 UTC, SamanthaDawsonBanks commented on mcomp_C/maths/Rotate.cpp
> + * Turn.cpp
old name

2018-03-23 09:39 UTC, SamanthaDawsonBanks commented on mcomp_C/maths/Rotate.h
> + * Turn.h
old name

2018-03-23 09:39 UTC, SamanthaDawsonBanks commented on mcomp_C/movement/driving.h
> -	void unlockMotors();
this may still need to be in the code somewhere - maybe a unlock() in movement? [also maybe a lock() so we can conditionally apply or release the brakes?]

2018-03-23 09:39 UTC, SamanthaDawsonBanks commented on mcomp_C/movement/driving.h
> -	~driving();
with the new structure I think AFMS is now self cleaning but just a note to check

2018-03-23 09:39 UTC, SamanthaDawsonBanks commented on mcomp_C/movement/Drive.cpp
> +
I think there are some math logic flow errors in there

2018-03-23 09:40 UTC, SamanthaDawsonBanks commented
I think the math needs a 2nd look but other wise all good

2018-03-23 10:03 UTC, stevempope commented on mcomp_C/maths/Forward.cpp
> +/*
This is a fair point. We had quite a discussion about it yesterday but it got a bit late so I ended up leaving them all where they were. Adjusted in latest commits.

2018-03-23 10:03 UTC, stevempope commented on mcomp_C/maths/Rotate.cpp
> + * Turn.cpp
Fair point, missed it when I used the Eclipse refactor tool.

2018-03-23 10:03 UTC, stevempope commented on mcomp_C/maths/Rotate.h
> + * Turn.h
As above for rotate.cpp.

2018-03-23 10:04 UTC, stevempope commented on mcomp_C/movement/driving.h
> -	void unlockMotors();
Good spot, I need to re-add that method.

2018-03-23 10:04 UTC, stevempope commented on mcomp_C/movement/driving.h
> -	~driving();
I believe that as AFMS is now a Global Variable it has just the one instance that is created and dies with the program.

2018-03-23 14:51 UTC, SamanthaDawsonBanks approved these changes
Looking good mate

2018-03-23 16:59 UTC, RyanShoobert approved these changes

2018-03-24 09:09 UTC, stevempope commented
Closing as it works, will raise a new PR to refine this. Main should include drive etc as libraries rather than libraries including main. In the same way, a sandwich depends on cheese and bread and bits existing rather than cheese depending on a sandwich existing. Analogies.

2018-03-24 09:09 UTC, merged